"""
Auto-generated test fixtures for the root Tests/ suite.
Generated by test_preparation.py.
"""

import json
import os
import sys
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE_DIR = REPO_ROOT / "Phase_2" / "Project" / "marketplace"
sys.path.insert(0, str(MARKETPLACE_DIR))

DB_FILE = REPO_ROOT / "test_db.sqlite3"
UPLOAD_DIR = REPO_ROOT / "test_uploads"

os.environ.setdefault("SECRET_KEY", "test-secret-key-do-not-use-in-prod-1234567890abcdef")
os.environ.setdefault("DATABASE_URL", f"sqlite:///{DB_FILE}")
os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("UPLOAD_DIR", str(UPLOAD_DIR))

from main import app as marketplace_app  # noqa: E402

test_app = FastAPI()
test_app.mount("/api/v1", marketplace_app)

SEED_FILE = Path(__file__).resolve().parent / "test_seed_data.json"
with open(SEED_FILE, "r", encoding="utf-8") as f:
    SEED = json.load(f)


@pytest.fixture
def client():
    return TestClient(test_app)


def _login_client(email: str, password: str):
    client = TestClient(test_app)
    response = client.post(
        "/api/v1/auth/login",
        json={"email": email, "password": password},
    )
    response.raise_for_status()
    token = response.json()["access_token"]
    client.headers["Authorization"] = f"Bearer {token}"
    return client


@pytest.fixture
def seed_buyer():
    return SEED["buyer_a"]


@pytest.fixture
def seed_seller():
    return SEED["seller_a"]


@pytest.fixture
def buyer_client():
    return _login_client(
        SEED["buyer_a"]["email"],
        SEED["buyer_a"]["password"],
    )


@pytest.fixture
def seller_client():
    return _login_client(
        SEED["seller_a"]["email"],
        SEED["seller_a"]["password"],
    )


@pytest.fixture
def buyer_a_client(buyer_client):
    return buyer_client


@pytest.fixture
def seller_a_client(seller_client):
    return seller_client


@pytest.fixture
def buyer_b_order_id():
    return SEED["buyer_b_order"]["id"]


@pytest.fixture
def seller_b_product_id():
    return SEED["seller_b_product"]["id"]


@pytest.fixture
def active_product():
    return SEED["active_product"]


@pytest.fixture
def delivered_order():
    return SEED["delivered_order"]
